[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FFFFFF"
backgroundColor = "#000000"
secondaryBackgroundColor = "#101010"
textColor = "#FFFFFF"
